import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";

type Control = {
  id: string;
  title: string;
  description: string;
  domain_name: string;
  status: string;
  notes: string;
};

type ReportData = {
  orgName: string;
  date: string;
  targetLevel: number;
  score: number;
  totalControls: number;
  met: number;
  notMet: number;
  partial: number;
  controls: Control[];
};

export function SSPReport({ data }: { data: ReportData }) {
  const grouped = new Map<string, Control[]>();
  data.controls.forEach((c) => {
    if (!grouped.has(c.domain_name)) grouped.set(c.domain_name, []);
    grouped.get(c.domain_name)!.push(c);
  });

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.logo}>CMMC-Ready</Text>
          <View style={styles.headerRight}>
            <Text>CONFIDENTIAL</Text>
            <Text>{data.date}</Text>
          </View>
        </View>

        <View style={{ marginTop: 80, alignItems: "center" }}>
          <Text style={{ fontSize: 28, fontFamily: "Helvetica-Bold", marginBottom: 12 }}>
            System Security Plan
          </Text>
          <Text style={{ fontSize: 14, color: "#525252", marginBottom: 8 }}>
            CMMC Level {data.targetLevel} Compliance
          </Text>
          <Text style={{ fontSize: 16, fontFamily: "Helvetica-Bold", marginTop: 30 }}>
            {data.orgName}
          </Text>
          <Text style={{ fontSize: 11, color: "#737373", marginTop: 8 }}>
            Prepared: {data.date}
          </Text>
          <Text style={{ fontSize: 11, color: "#737373", marginTop: 4 }}>
            Generated by CMMC-Ready Platform
          </Text>
        </View>

        <View style={{ marginTop: 60 }}>
          <Text style={styles.sectionTitle}>Document Control</Text>
          <View style={styles.table}>
            <View style={styles.tableRow}>
              <Text style={[styles.tableCell, { width: 150, ...styles.bold }]}>Document Title</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>System Security Plan (SSP)</Text>
            </View>
            <View style={styles.tableRowAlt}>
              <Text style={[styles.tableCell, { width: 150, ...styles.bold }]}>Organization</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>{data.orgName}</Text>
            </View>
            <View style={styles.tableRow}>
              <Text style={[styles.tableCell, { width: 150, ...styles.bold }]}>CMMC Target Level</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>Level {data.targetLevel}</Text>
            </View>
            <View style={styles.tableRowAlt}>
              <Text style={[styles.tableCell, { width: 150, ...styles.bold }]}>Date Prepared</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>{data.date}</Text>
            </View>
            <View style={styles.tableRow}>
              <Text style={[styles.tableCell, { width: 150, ...styles.bold }]}>Compliance Score</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>{data.score}% ({data.met}/{data.totalControls} controls met)</Text>
            </View>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>CMMC-Ready | System Security Plan</Text>
          <Text>CONFIDENTIAL</Text>
        </View>
      </Page>

      {/* Executive Summary */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.logo}>CMMC-Ready</Text>
          <View style={styles.headerRight}>
            <Text>{data.orgName}</Text>
            <Text>SSP — {data.date}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.text}>
          This System Security Plan (SSP) documents the security controls implemented by {data.orgName} to protect Controlled Unclassified Information (CUI) in accordance with CMMC Level {data.targetLevel} requirements.
        </Text>

        <View style={styles.scoreBox}>
          <View style={styles.scoreItem}>
            <Text style={[styles.scoreValue, { color: "#2563eb" }]}>{data.score}%</Text>
            <Text style={styles.scoreLabel}>OVERALL SCORE</Text>
          </View>
          <View style={styles.scoreItem}>
            <Text style={[styles.scoreValue, { color: "#16a34a" }]}>{data.met}</Text>
            <Text style={styles.scoreLabel}>CONTROLS MET</Text>
          </View>
          <View style={styles.scoreItem}>
            <Text style={[styles.scoreValue, { color: "#dc2626" }]}>{data.notMet}</Text>
            <Text style={styles.scoreLabel}>GAPS</Text>
          </View>
          <View style={styles.scoreItem}>
            <Text style={[styles.scoreValue, { color: "#ca8a04" }]}>{data.partial}</Text>
            <Text style={styles.scoreLabel}>PARTIAL</Text>
          </View>
        </View>

        <Text style={styles.text}>
          The assessment covers {data.totalControls} security controls across 14 domains as defined in NIST SP 800-171 and mapped to the CMMC 2.0 framework. {data.met} controls have been fully implemented, {data.partial} are partially implemented, and {data.notMet} require remediation.
        </Text>

        <View style={styles.footer}>
          <Text>CMMC-Ready | System Security Plan</Text>
          <Text>Page 2</Text>
        </View>
      </Page>

      {/* Control Details by Domain */}
      {Array.from(grouped.entries()).map(([domain, controls], pageIdx) => (
        <Page key={domain} size="A4" style={styles.page}>
          <View style={styles.header}>
            <Text style={styles.logo}>CMMC-Ready</Text>
            <View style={styles.headerRight}>
              <Text>{data.orgName}</Text>
              <Text>SSP — {data.date}</Text>
            </View>
          </View>

          <Text style={styles.sectionTitle}>{domain}</Text>

          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderCell, { width: 80 }]}>Control ID</Text>
              <Text style={[styles.tableHeaderCell, { flex: 1 }]}>Title</Text>
              <Text style={[styles.tableHeaderCell, { width: 70 }]}>Status</Text>
            </View>
            {controls.map((c, i) => (
              <View key={c.id} style={i % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
                <Text style={[styles.tableCell, { width: 80, fontFamily: "Helvetica-Bold", fontSize: 8 }]}>{c.id}</Text>
                <Text style={[styles.tableCell, { flex: 1 }]}>{c.title}</Text>
                <Text
                  style={[
                    c.status === "met" ? styles.statusMet :
                    c.status === "not_met" ? styles.statusNotMet :
                    styles.statusPartial,
                    { width: 70 },
                  ]}
                >
                  {c.status === "met" ? "MET" : c.status === "not_met" ? "NOT MET" : c.status === "partially_met" ? "PARTIAL" : "N/A"}
                </Text>
              </View>
            ))}
          </View>

          <View style={styles.footer}>
            <Text>CMMC-Ready | System Security Plan</Text>
            <Text>Page {pageIdx + 3}</Text>
          </View>
        </Page>
      ))}

      {/* Signature Page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.logo}>CMMC-Ready</Text>
          <View style={styles.headerRight}>
            <Text>{data.orgName}</Text>
            <Text>SSP — {data.date}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Authorization & Signatures</Text>
        <Text style={styles.text}>
          By signing below, the undersigned acknowledge that this System Security Plan accurately represents the security posture of {data.orgName} and authorize its use for CMMC assessment purposes.
        </Text>

        <View style={styles.signatureBlock}>
          <View>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>System Owner</Text>
            <Text style={[styles.signatureLabel, { marginTop: 2 }]}>Date: _______________</Text>
          </View>
          <View>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Information System Security Officer</Text>
            <Text style={[styles.signatureLabel, { marginTop: 2 }]}>Date: _______________</Text>
          </View>
        </View>

        <View style={[styles.signatureBlock, { marginTop: 20 }]}>
          <View>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Authorizing Official</Text>
            <Text style={[styles.signatureLabel, { marginTop: 2 }]}>Date: _______________</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>CMMC-Ready | System Security Plan</Text>
          <Text>CONFIDENTIAL</Text>
        </View>
      </Page>
    </Document>
  );
}
